# Generated by Django 2.2.10 on 2020-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('TEXT', 'Text response'), ('ONE_CHOICE', 'One choice response'), ('MULTIPLE_CHOICE', 'Multiple choice response')], default='TEXT', max_length=255)),
            ],
        ),
    ]
