# Generated by Django 2.2.10 on 2020-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField(auto_now=True)),
                ('questions', models.ManyToManyField(to='core.Question')),
            ],
        ),
    ]
