# Generated by Django 2.2.10 on 2020-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200516_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
